dataset_name = 'kitti'
dataset_dir = 'E:/Depth/target_dataset/kitti'
folder_type = 'sequence'
load_pseudo_depth = False
model = 'sc-depth-pl'
exp_name = 'sc-depth-pl-kitti'
val_model = 'depth'
use_frame_index = False
height = 256
width = 832
epoch_size=100
resnet_layers=18
img_suffix='*.jpg'
depth_suffix='*.npz'
