exp_name = 'kitti_scv1'
dataset_dir = 'E:/Depth/target_dataset/kitti'
folder_type = 'sequence'
dataset_name = 'kitti'
resnet_layers = 18
val_model = 'depth'
lr = 1e-3
warmup_lr= 3e-4  # 预热学习率
min_lr= 1e-6  # 最小的学习率
batch_size = 6
epochs = 100
epoch_size = 100
img_suffix='*.jpg'
depth_suffix='*.npz'